config/routes.rb
App::Application.routes.draw do
  get "sessions/new"
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :documents
  resources :sections,          only: [:create, :destroy, :show, :index] 

  resources :users
  resources :docs,          only: [:create, :destroy, :show] 

  

end

app/models/doc.rb
class Doc < ActiveRecord::Base
   belongs_to :user
   default_scope -> { order('created_at DESC') }
   validates :user_id, presence: true
   validates :title, presence: true
   validates :content, presence: true
 
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :show]

  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      flash[:success] = "Document created!"
      redirect_to user_path(current_user)
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

  def show
    @doc = current_user.docs.find(params[:id])
  end

  private

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_doc.html.erb
<li id="doc-<%= doc.id %>">
  <span class="user">
    <%= link_to doc.title, doc_path(doc.id) %>
  </span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(doc.created_at) %> ago.
  </span>
</li>

app/views/docs/show.html.erb
<h3>
  <%= @doc.title %>
</h3>




<div class="row">
  <div class="col-md-8">
      <%= simple_format(@doc.content) %>
  </div>

</div>