config/routes.rb
App::Application.routes.draw do
  get "sessions/new"
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :documents
  resources :sections,          only: [:create, :destroy, :show, :index] 

  resources :users
  resources :docs,          only: [:create, :destroy, :show] 

  

end

app/models/document.rb
class Document < ActiveRecord::Base
   belongs_to :user

   validates :user_id, presence: true
   validates :title, presence: true
   validates :content, presence: true

   has_many :sections, dependent: :destroy
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :show, :index]

  def create
    @document = current_user.documents.build(document_params)
    if @document.save
      flash[:success] = "Document created!"
      redirect_to user_path(current_user)
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

  def index
    @document = Document.new if logged_in?
  end 

  def show
    @document = current_user.documents.find(params[:id])
    @doc = Doc.new if logged_in?
    @section = Section.new if logged_in?
  end

  private

    def document_params
      params.require(:document).permit(:title, :content)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<li>
  <%= link_to document.title, document %>

  <%= link_to "delete", document, method: :delete,
                                  data: { confirm: "You sure?" } %>


</li>

app/views/documents/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>

<%= f.label :content %>
<%= f.text_area :content,  :cols => "30", :rows => "10",  class: 'form-control' %>

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content,  :cols => "30", :rows => "10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<% provide(:title, "Edit document") %>
<h1>Update your document</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@document) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/documents/index.html.erb
<% provide(:title, 'All documents') %>
<h1>All documents</h1>

<ul class="documents">
    <li>
      <%= render current_user.documents %>
    </li>
</ul>

<br>

<h1>Create a new document</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@document) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
 
 <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content,  :cols => "30", :rows => "10" %>
  </div>


  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
  </div>
</div>

app/views/documents/new.html.erb
<% provide(:title, 'Create a new document') %>
<h1>Create a new document</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@document) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
 
 <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content,  :cols => "30", :rows => "10" %>
  </div>


  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
  </div>
</div>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= simple_format(@document.content) %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

<h3>Save this document</h3>


<%= form_for(@doc) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
 
    <%= f.hidden_field :title, :value => @document.title %>


    <%= f.hidden_field :content,  :cols => "30", :rows => "10", :value => @document.content %>



  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="section_form">
        <%= render 'shared/section_form' %>
      </section>
    </aside>
  </div>

<div class="col-md-8">
    <% if @document.sections.any? %>
      <h3>Sections (<%= @document.sections.count %>)</h3>
      <ol class="sections">
        <%= render @document.sections %>
      </ol>
    <% end %>
</div>